---
# ! If this task ran,
# make changes in ansible.cfg and update sudo_pub_key
# variables in inventories/group_vars/all.yml
#
- name: Old ssh-key remover
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ sudo_pub_key_to_remove }}"
    state: absent

- name: SSH reloader
  ansible.builtin.service:
    name: ssh
    state: reloaded
