---
- name: Setup packages
  ansible.builtin.include_tasks:
    file: roles/common/tasks/setup-packages.yml

- name: Setup users
  ansible.builtin.include_tasks:
    file: roles/common/tasks/setup-users.yml
