---
- name: Check if 'Terraform' user exist
  ansible.builtin.slurp:
    src: /etc/pve/user.cfg
  register: file_content

- name: Create 'Terraform' user
  when: "'TerraformProv' not in (file_content.content | b64decode)"
  ansible.builtin.shell: |
    pveum role add TerraformProv -privs "{{ terraform_privileges }}"
    pveum user add "{{ terraform_user }}"@pve --password "{{ terraform_password }}"
    pveum aclmod / -user "{{ terraform_user }}"@pve -role TerraformProv
    exit 0
