---
# -----------------------------------------------------------------------------------+
# Proxmox homelab inventories example.
# -----------------------------------------------------------------------------------+
#
homelab:
  children:
    node_gate:
      hosts:
        192.168.1.100
    nodes_k8s:
      hosts:
        192.168.1.101
        192.168.1.102
        192.168.1.103
  vars:
    ansible_port: "{{ sudo_port }}"
    ansible_user: "{{ sudo_user }}"
    ansible_become_password: "{{ sudo_password }}"
