---
# -----------------------------------------------------------------------------------+
# Proxmox homelab inventories example.
# -----------------------------------------------------------------------------------+
#
homelab:
  children:
    nodes:
      hosts:
        192.168.1.100
  vars:
    ansible_port: "{{ sudo_port }}"
    ansible_user: "{{ sudo_user }}"
    ansible_become_password: "{{ sudo_password }}"
