---
# https://docs.ansible.com/ansible/2.8/user_guide/playbooks_best_practices.html
#
- name: Keeps ssh-keys, users and passwords updated
  hosts: all
  become: true
  roles:
    - security

- name: Keeps packages updated
  hosts: all
  become: true
  roles:
    - common
